version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: moodle_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  moodle:
    build: .
    container_name: moodle_web
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - moodle:/var/www/html/moodle

volumes:
  db_data:
  moodle:
